name: 'tongueformer 119'
data:
  train:
    path: 'w2v/1.0/c/nonorm_azel/train_data_50fps.npy'
    num_files: 1600
    num_workers: 16
    win_sz: 5
    win_stride: 1
    pose_only: False
  valid:
    path: 'w2v/1.0/c/nonorm_azel/valid_data_50fps.npy'
    num_files: 400
    num_workers: 16
    win_sz: 5
    win_stride: 1
    pose_only: False
training: 
  num_epochs: 1000
  batch_sz: 256
  loss: 
    label: 'mse'
    params: None
  output_idx: 2
  output_full: False
  early_stop: 100
optim:
  label: 'adam'
  params:
    lr: 1e-7
    weight_decay: 0.0
scheduler:
  label: None
model:
  multi_gpu: False
  params:
    num_frames: 5
    in_feat_dim: 1024
    out_idx: 2
    out_full: False
    num_joints: 10
    num_layers: 16
    num_heads: 8
    mlp_ratio: 1
    qkv_bias: True
    qk_scale: None
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.2
    norm_layer: None
    mask: None
    deeper_fc: False
  save_dir: 'train/w2v/1.0/c/pose/tongueformer/v119/'
log:
  save_dir: 'train/w2v/1.0/c/pose/tongueformer/v119/'