name: 'tongueformer 002'
data:
  train:
    path: 'w2v/1.0/c/nonorm_azel/train_data_50fps.npy'
    num_files: 1600
    num_workers: 16
    win_sz: 50
    win_stride: 1
    pose_only: False
  valid:
    path: 'w2v/1.0/c/nonorm_azel/valid_data_50fps.npy'
    num_files: 400
    num_workers: 16
    win_sz: 50
    win_stride: 1
    pose_only: False
training: 
  num_epochs: 20
  batch_sz: 64
  learning_rate: 1e-5
  loss: 'mse'
  output_idx: 24
  early_stop: 10
model:
  multi_gpu: False
  params:
    num_frames: 50
    in_feat_dim: 1024
    num_joints: 10
    num_layers: 2
    num_heads: 4
    mlp_ratio: 2
    qkv_bias: True
    qk_scale: None
    drop_rate: 0.
    attn_drop_rate: 0.
    drop_path_rate: 0.2
    norm_layer: None
    mask: None
  save_dir: 'train/w2v/1.0/c/pose/tongueformer/v002/'
log:
  save_dir: 'train/w2v/1.0/c/pose/tongueformer/v002/'