name: 'tongueformer 011'
data:
  train:
    path: 'w2v/1.0/c/nonorm_azel/train_data_50fps.npy'
    num_files: 1600
    num_workers: 16
    win_sz: 7
    win_stride: 1
    pose_only: False
  valid:
    path: 'w2v/1.0/c/nonorm_azel/valid_data_50fps.npy'
    num_files: 400
    num_workers: 16
    win_sz: 7
    win_stride: 1
    pose_only: False
training: 
  num_epochs: 300
  batch_sz: 32
  learning_rate: 1e-7
  loss: 'mse'
  output_idx: 5
  early_stop: 10
model:
  multi_gpu: False
  params:
    num_frames: 7
    in_feat_dim: 1024
    num_joints: 10
    num_layers: 4
    num_heads: 8
    mlp_ratio: 1
    qkv_bias: True
    qk_scale: None
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.2
    norm_layer: None
    mask: None
  save_dir: 'train/w2v/1.0/c/pose/tongueformer/v011/'
log:
  save_dir: 'train/w2v/1.0/c/pose/tongueformer/v011/'