data: 
  train_path: 'ds/nonorm_azel/train_data_50fps.npy'
  valid_path: 'ds/nonorm_azel/valid_data_50fps.npy'
  num_train_files: 1600
  num_dataload_workers: 10
  win_sz: 50
  win_stride: 1
training:
  multi_gpu: False
  num_epochs: 40
  batch_sz: 32
  dropout: 0.25
  learning_rate: 1e-5
  loss: 'mse'
model: 
  input_sz: 1024
  hidden_sz: 512
  output_sz: 30
  num_layers: 1
  bidirectional: True
  save_dir: 'train/ds/pose/lstm/mse/bidir/lstm_1l'
log:
  save_dir: 'train/ds/pose/lstm/mse/bidir/lstm_1l'