data: 
  train_path: 'mfa/nonorm_azel/train_data_50fps.npy'
  valid_path: 'mfa/nonorm_azel/valid_data_50fps.npy'
  num_train_files: 1600
  num_dataload_workers: 10
  input_win_sz: 50
  output_win_sz: 15
  win_stride: 1
training:
  multi_gpu: False
  num_epochs: 80
  batch_sz: 32
  dropouts: [0., 0.]
  learning_rate: 5e-5
  loss: 'mse'
model: 
  input_sz: 3600
  hidden_szs: [2048, 1024]
  output_sz: 450
  save_dir: 'train/mfa/pose/mlp/mse/mlp_50v15'
log:
  save_dir: 'train/mfa/pose/mlp/mse/mlp_50v15'