name: 'tongueformer 038 ds'
data:
  train:
    path: 'ds/nonorm_azel/train_data_50fps.npy'
    num_files: 1600
    num_workers: 16
    win_sz: 15
    win_stride: 1
    pose_only: False
  valid:
    path: 'ds/nonorm_azel/valid_data_50fps.npy'
    num_files: 400
    num_workers: 16
    win_sz: 15
    win_stride: 1
    pose_only: False
training: 
  num_epochs: 1000
  batch_sz: 128
  learning_rate: 5e-8
  loss: 
    label: 'huber'
    params:
      delta: 1.0
  output_idx: -1
  output_full: True
  early_stop: 10
model:
  multi_gpu: False
  params:
    num_frames: 15
    in_feat_dim: 1024
    out_idx: -1
    out_full: True
    num_joints: 10
    num_layers: 6
    num_heads: 8
    mlp_ratio: 2
    qkv_bias: True
    qk_scale: None
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.2
    norm_layer: None
    no_peek: True
  save_dir: 'train/ds/pose/tongueformer/v038/'
log:
  save_dir: 'train/ds/pose/tongueformer/v038/'
