data: 
  train_path: 'mfcc/nonorm_azel/train_data_50fps.npy'
  valid_path: 'mfcc/nonorm_azel/valid_data_50fps.npy'
  num_train_files: 1600
  num_dataload_workers: 10
  input_win_sz: 15
  output_win_sz: 5
  win_stride: 1
training:
  multi_gpu: False
  num_epochs: 40
  batch_sz: 32
  dropouts: [0., 0.]
  learning_rate: 5e-5
  loss: 'mse'
model: 
  input_sz: 405
  hidden_szs: [512, 256]
  output_sz: 150
  save_dir: 'train/mfcc/pose/mlp/mse/mlp_15v5'
log:
  save_dir: 'train/mfcc/pose/mlp/mse/mlp_15v5'
checkpoint:
  path: 'train/mfcc/pose/mlp/mse/mlp_15v5/120.pt'