data:
  type: mocap
  train_path: 'w2v/1.0/rt/300ms/train_data_100fps.npy'
  valid_path: 'w2v/1.0/rt/300ms/valid_data_100fps.npy'
  num_train_files: 1600
  num_dataload_workers: 10
  input_win_sz: 15
  output_win_sz: 5
  win_stride: 1
training:
  multi_gpu: False
  num_epochs: 100
  batch_sz: 32
  dropouts: [0., 0.]
  learning_rate: 1e-5
  loss:
    label: 'mse'
  early_stop: 50
validation:
  mode: last-one
model: 
  input_sz: 7680
  hidden_sz: [2048, 512]
  output_sz: 150
  use_att: False
  att_sz: 512
  save_dir: 'train/w2v/1.0/rt/300ms/pose/mlp_15v5'
log:
  save_dir: 'train/w2v/1.0/rt/300ms/pose/mlp_15v5'