data: 
  train_path: 'mfcc/nonorm_azel/train_data_50fps.npy'
  valid_path: 'mfcc/nonorm_azel/valid_data_50fps.npy'
  num_train_files: 1600
  num_dataload_workers: 10
  win_sz: 15
  win_stride: 1
training:
  multi_gpu: False
  num_epochs: 40
  batch_sz: 32
  dropout: 0.25
  learning_rate: 1e-5
  loss: 'mse'
  early_stop: 10
model: 
  input_sz: 27
  hidden_sz: 512
  output_sz: 30
  num_layers: 5
  bidirectional: False
  save_dir: 'train/mfcc/pose/gru/mse/unidir/5l/in_15'
log:
  save_dir: 'train/mfcc/pose/gru/mse/unidir/5l/in_15'